name: First Workflow
#event that triggers action is push
on: [push]

jobs:
  run-shell-commands:
    runs-on: macos-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command
        run: |
          node -v
          npm -v